=== thavetta/xmlxsd/Laby/Lab02a/Start/Knihovna.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 sp1 (x64) (http://www.altova.com) by Tomáš Havetta (TRIGAN, s r.o.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Knihovna">
		<xs:annotation>
			<xs:documentation>Seznam knih</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Kniha" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Autori">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Autor" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="Jmeno" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Nazev"/>
							<xs:element name="Nakladatel"/>
							<xs:element name="RokVydani"/>
						</xs:sequence>
						<xs:attribute name="ISBN"/>
						<xs:attribute name="Jazyk"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== thavetta/xmlxsd/Laby/Lab02a/Start/Knihovna.xml
<?xml version="1.0" encoding="UTF-8"?>
<Knihovna xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Knihovna.xsd">
	<Kniha ISBN="123456" Jazyk="cs">
		<Autori>
			<Autor Jmeno="Juraj Červenák"/>
		</Autori>
		<Nazev>Ďáblova pevnost</Nazev>
		<Nakladatel>BROKILON</Nakladatel>
		<RokVydani>2011</RokVydani>
	</Kniha>
	<Kniha ISBN="1234567" Jazyk="cs">
		<Autori>
			<Autor Jmeno="Juraj Červenák"/>
		</Autori>
		<Nazev>Strážcové Varadínu</Nazev>
		<Nakladatel>BROKILON</Nakladatel>
		<RokVydani>2009</RokVydani>
	</Kniha>
	<Kniha ISBN="12345678" Jazyk="cs">
		<Autori>
			<Autor Jmeno="Milan Lasica"/>
			<Autor Jmeno="Jiří Stránský"/>
		</Autori>
		<Nazev>Dopisy bez hranic</Nazev>
		<Nakladatel>Andrej Šťastný</Nakladatel>
		<RokVydani>2010</RokVydani>
	</Kniha>
</Knihovna>
