=== thavetta/xmlxsd/Laby/Lab03/Final/Knihovna.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 sp1 (x64) (http://www.altova.com) by Tomáš Havetta (TRIGAN, s r.o.) -->
<xs:schema xmlns:g="http://www.gopas.cz/kurz/xmlxsd/2019" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:p="http://www.gopas.cz/kurz/popis/2019" targetNamespace="http://www.gopas.cz/kurz/xmlxsd/2019" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.gopas.cz/kurz/popis/2019" schemaLocation="Popis.xsd"/>
	<xs:element name="Knihovna">
		<xs:annotation>
			<xs:documentation>Seznam knih</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Kniha" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Autori">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Autor" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="Jmeno" type="xs:token" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Nazev" type="xs:token"/>
							<xs:element name="Nakladatel">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="BROKILON"/>
										<xs:enumeration value="Andrej Šťastný"/>
										<xs:enumeration value="Albatros"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RokVydani">
								<xs:simpleType>
									<xs:union memberTypes="xs:gYear">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="neznámý"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:union>
								</xs:simpleType>
							</xs:element>
							<xs:element ref="p:Popis"/>
							<xs:element ref="p:Odkaz" minOccurs="0"/>
							<xs:any namespace="http://www.gopas.cz/kurz/test2019" processContents="lax" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="ID" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token">
									<xs:pattern value="[BDVMPY]-\d{5}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ISBN" type="xs:token"/>
						<xs:attribute name="Cena">
							<xs:simpleType>
								<xs:restriction base="xs:decimal">
									<xs:fractionDigits value="2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="PocetStranek" type="xs:unsignedShort"/>
						<xs:attribute name="Zapujcena" type="xs:boolean"/>
						<xs:attribute name="Jazyk" type="xs:language"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="SeznamSlov">
		<xs:list itemType="xs:string"/>
	</xs:simpleType>
</xs:schema>

=== thavetta/xmlxsd/Laby/Lab03/Final/Knihovna.xml
<?xml version="1.0" encoding="UTF-8"?>
<Knihovna xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gopas.cz/kurz/xmlxsd/2019 Knihovna.xsd" xmlns="http://www.gopas.cz/kurz/xmlxsd/2019" xmlns:p="http://www.gopas.cz/kurz/popis/2019"
xmlns:a="http://www.gopas.cz/kurz/test2019">
	<Kniha ID="B-00001" ISBN="123456" Jazyk="cs" PocetStranek="491" Cena="299.90" Zapujcena="true">
		<Autori>
			<Autor Jmeno="Juraj Červenák"/>
		</Autori>
		<Nazev>Ďáblova pevnost</Nazev>
		<Nakladatel>BROKILON</Nakladatel>
		<RokVydani>2011</RokVydani>
		<p:Popis>Historie a fikce</p:Popis>
	</Kniha>
	<Kniha ID="B-00002" ISBN="1234567" Jazyk="cs" PocetStranek="525" Cena="149" Zapujcena="false">
		<Autori>
			<Autor Jmeno="Juraj Červenák"/>
		</Autori>
		<Nazev>Strážcové Varadínu</Nazev>
		<Nakladatel>BROKILON</Nakladatel>
		<RokVydani>2009</RokVydani>
		<p:Popis>Historie a fikce turecke valky</p:Popis>
		<p:Odkaz>http://www.knihy.cz/cervenak/varadin.html</p:Odkaz>
	</Kniha>
	<Kniha ID="M-00003" ISBN="12345678" Jazyk="cs" Zapujcena="0">
		<Autori>
			<Autor Jmeno="Milan Lasica"/>
			<Autor Jmeno="Jiří Stránský"/>
		</Autori>
		<Nazev>Dopisy bez hranic</Nazev>
		<Nakladatel>Andrej Šťastný</Nakladatel>
		<RokVydani>neznámý</RokVydani>
		<p:Popis>Pohled na existenci z jineho uhlu 1 2 3 4</p:Popis>
		<a:Pokus>Cokoliv</a:Pokus>
	</Kniha>
</Knihovna>
