=== thavetta/xmlxsd/Laby/Lab02a/Final/Knihovna.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 sp1 (x64) (http://www.altova.com) by Tomáš Havetta (TRIGAN, s r.o.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Knihovna">
		<xs:annotation>
			<xs:documentation>Seznam knih</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Kniha" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Autori">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Autor" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="Jmeno" type="xs:token" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Nazev" type="xs:token"/>
							<xs:element name="Nakladatel">
								<xs:simpleType>
									<xs:restriction base="xs:token"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="RokVydani">
								<xs:simpleType>
									<xs:restriction base="xs:gYear"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Popis">
								<xs:simpleType>
									<xs:restriction base="xs:string"/>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Odkaz" type="xs:anyURI" minOccurs="0"/>
						</xs:sequence>
						<xs:attribute name="ID" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:token"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="ISBN" type="xs:token"/>
						<xs:attribute name="Cena">
							<xs:simpleType>
								<xs:restriction base="xs:decimal"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="PocetStranek" type="xs:unsignedShort"/>
						<xs:attribute name="Zapujcena" type="xs:boolean"/>
						<xs:attribute name="Jazyk" type="xs:language"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== thavetta/xmlxsd/Laby/Lab02a/Final/Knihovna.xml
<?xml version="1.0" encoding="UTF-8"?>
<Knihovna xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Knihovna.xsd">
	<Kniha ID="A001" ISBN="123456" Jazyk="cs" PocetStranek="491" Cena="299.90" Zapujcena="true">
		<Autori>
			<Autor Jmeno="Juraj Červenák"/>
		</Autori>
		<Nazev>Ďáblova pevnost</Nazev>
		<Nakladatel>BROKILON</Nakladatel>
		<RokVydani>2011</RokVydani>
		<Popis>Historie a fikce</Popis>
	</Kniha>
	<Kniha ID="A002" ISBN="1234567" Jazyk="cs" PocetStranek="525" Cena="149" Zapujcena="false">
		<Autori>
			<Autor Jmeno="Juraj Červenák"/>
		</Autori>
		<Nazev>Strážcové Varadínu</Nazev>
		<Nakladatel>BROKILON</Nakladatel>
		<RokVydani>2009</RokVydani>
		<Popis>Historie a fikce turecke valky</Popis>
		<Odkaz>http://www.knihy.cz/cervenak/varadin.html</Odkaz>
	</Kniha>
	<Kniha ID="A003" ISBN="12345678" Jazyk="cs" Zapujcena="0">
		<Autori>
			<Autor Jmeno="Milan Lasica"/>
			<Autor Jmeno="Jiří Stránský"/>
		</Autori>
		<Nazev>Dopisy bez hranic</Nazev>
		<Nakladatel>Andrej Šťastný</Nakladatel>
		<RokVydani>2010</RokVydani>
		<Popis>Pohled na existenci z jineho uhlu</Popis>
	</Kniha>
</Knihovna>
